#!/usr/nbin/env python3
#-*- coding:utf-8 -*-

BOARDCAST_ADDR	= "ffffffffffff"
RESPONSE_TOPIC	= "/acs/response"
CONCTRL_TOPIC_HEAD	= "/acs/ctrl/"
COMMON_TOPIC	= "/acs/ask"

DOORSTONE="iotwonderful"
UPGRADE_TOKEN_URL=
UPGRADE_USERNAME=
UPGRADE_PASSWORD=

RESPONSE_MSG = {
	"resp" : 1,
	"sn" : 010203040506,
	"time" : 1,
	"identify" : 55555,
}

MQTT_CMD_CHECKSTATUS	= 1
MQTT_CMD_OPENDOOR		= 2
MQTT_CMD_QR_BY_WX		= 3
MQTT_CMD_QR_DOWNLOAD	= 4
MQTT_CMD_QR_BY_SELF		= 5
MQTT_CMD_SET_GROUP		= 6
MQTT_CMD_SET_DOORLOCKTIME	= 7
MQTT_CMD_UPDATE			= 8
MQTT_CMD_SET_OPENSSH	= 9
MQTT_CMD_WLAN			= 10

MQTT_RESP_INVAILD		= 50
MQTT_RESP_TIMEOUT		= 51
MQTT_RESP_DEIVCE_BUSY	= 52
MQTT_RESP_ONLINE		= 200
MQTT_RESP_OFFLINE		= 201
MQTT_UPGRADE_IGNORE		= 202
MQTT_UPGRADE_READY		= 203
MQTT_UPGRADE_DOWNLOAD	= 204


